# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftLoginView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'RxSwift', '~> 3.6'
pod 'RxCocoa', '~> 3.6'
  # Pods for RxSwiftLoginView

end
